### ISSUE TITLE
pressfit endstop plug not reliable

### ISSUE THREAD

**Issue by tomaski** [EVA-3D/addon-mgn15#1]
when bumping the frame during sensorless homing, plug retracts.

**Comment by pkucmus** [comment]
bummer I had high hopes it would work on MNG12 as well, but I think I have an idea

**Comment by tomaski** [comment]
Maybe slightly widening the plug (moves way too freely) and making it tad
bit taller (would then be squeezed in and held in place by the linear block
screws)

pon., 23 lis 2020, 12:56 użytkownik Paweł Kucmus <notifications@github.com>
napisał:

**Comment by pkucmus** [comment]
Please check this one: https://cad.onshape.com/documents/551442bc5664b4216eddf506/w/16749997681c8bec66757f15/e/ea4ec7fbee5ff4345d4fa96a

**Comment by pkucmus** [comment]
Fixed and tested by me: https://eva-3d.github.io/eva-main/addons/x_endstop/ does not look like it but it's plenty strong in the X axis when on a printer
